services:
  cpu_base:
    build:
      context: ../
      dockerfile: dockerfiles/ros.dockerfile
      args:
        BASE_IMAGE: ubuntu:22.04
    image: roborregos/vsss_sim:cpu_base

  cuda_base:
    build:
      context: ../
      dockerfile: dockerfiles/ros.dockerfile
      args:
        BASE_IMAGE: nvidia/cuda:11.8.0-runtime-ubuntu22.04
    image: roborregos/vsss_sim:cuda_base

  vsss_sim_cuda:
    build:
      context: ../
      dockerfile: dockerfiles/vsss_sim.dockerfile
      args:
        BASE_IMAGE: ${vsss_sim_BASE_IMAGE}
    image: roborregos/vsss_sim:${vsss_sim_BASE_IMAGE_TAG}
    container_name: vsss_sim_cuda
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - LIBGL_ALWAYS_INDIRECT=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../../:/ros/vsss_ws/src/
    devices:
      - /dev/dri:/dev/dri
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    command: []
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  vsss_sim_gpu:
    build:
      context: ../
      dockerfile: dockerfiles/vsss.dockerfile
      args:
        BASE_IMAGE: ${vsss_sim_BASE_IMAGE}
    image: roborregos/vsss_sim_gpu:${vsss_sim_BASE_IMAGE_TAG}
    container_name: vsss_sim_gpu
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - LIBGL_ALWAYS_INDIRECT=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../../:/ros/vsss_ws/src/
    devices:
      - /dev/dri:/dev/dri
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    command: []
    
  
  vsss_sim_cpu:
    build:
      context: ../
      dockerfile: dockerfiles/vsss.dockerfile
      args:
        BASE_IMAGE: ${vsss_sim_BASE_IMAGE}
    image: roborregos/vsss_sim_cpu:${vsss_sim_BASE_IMAGE_TAG}
    container_name: vsss_sim_cpu
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../../:/ros/vsss_ws/src/
    stdin_open: true
    tty: true
    privileged: true
    command: []
